from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import Counter, defaultdict
from copy import deepcopy
from pathlib import Path
from typing import Any

PREFERRED_DUPLICATE_OCCURRENCE: dict[str, int] = {
    "1801.00375_gap_0": 1,
    "1905.07500_gap_1": 1,
    "1905.07500_gap_5": 1,
    "1910.01874_gap_1": 1,
    "1910.01874_gap_6": 1,
    "1910.02111_gap_0": 1,
    "1910.02111_gap_9": 1,
    "1907.11400_gap_0": 0,
    "1909.00034_gap_1": 1,
    "1910.01360_gap_0": 0,
    "2001.01410_gap_0": 2,
    "2107.06236_gap_0": 1,
    "2407.19878v5_gap_0": 0,
    "2101.04162_gap_1": 1,
    "2101.09861_gap_0": 0,
    "2101.09861_gap_1": 0,
    "2111.11975_gap_0": 1,
    "2204.08678_gap_0": 1,
    "1804.10581v2_gap_4": 1,
    "2109.00530_gap_0": 1,
    "2211.15609v4_gap_0": 1,
}

SPLIT_DUPLICATE_INSTANCE_IDS: dict[str, list[str]] = {
    "2111.11563_gap_0": ["2111.11563_gap_0_a", "2111.11563_gap_0_b"],
}

MANUAL_FIXES: dict[str, dict[str, Any]] = {
    "2310.19648v3_gap_0": {
        "x.anchor_hint": "Use Gordon-Litherland's identification of the symmetrized Seifert pairing of a chessboard surface of an alternating diagram with the flow lattice of the Tait graph.",
        "y.reference_tool_latex": "If $S$ is a chessboard surface of an alternating diagram $D$ with Tait graph $G$, then $(H_1(S),\\lambda_S)$ is isometric, up to overall sign, to the lattice $\\mathcal{F}(G)$ of integer-valued flows on $G$.",
        "y.reference_tool_type": "theorem",
    },
    "2311.09374v3_gap_0": {
        "x.anchor_hint": "Use upper semicontinuity of the entropy map on invariant measures to deduce existence of an equilibrium state.",
        "y.reference_tool_latex": "If the entropy map $\\mathcal{H}:\\mathcal{M}(X,T)\\to\\mathbb{R}$ is upper semicontinuous, then every continuous potential admits an equilibrium state.",
        "y.reference_tool_type": "theorem",
    },
    "1911.07306_gap_0": {
        "x.anchor_hint": "Apply the identity $\\sum_e w_e R_e^G = n-1$ to bound the total sampling probability by $O(n/\\epsilon^2)$.",
        "y.reference_tool_latex": "For a connected weighted graph $G$, \\[ \\sum_e w_e R_e^G = n-1. \\]",
        "y.reference_tool_type": "theorem",
    },
    "2011.12240_gap_0": {
        "x.anchor_hint": "Apply Artin's contractibility criterion using the anti-ample normal bundle of $X \\subset \\overline{M}_X(v)$.",
        "y.reference_tool_latex": "If a closed subvariety has anti-ample normal bundle, then it can be contracted to an algebraic space by a morphism that is an isomorphism away from that subvariety.",
        "y.reference_tool_type": "criterion",
    },
    "2109.10704_gap_0": {
        "x.anchor_hint": "Use the Contreras-Paternain hyperbolicity criterion to deduce that the closure of the periodic geodesics is a hyperbolic invariant set.",
        "y.reference_tool_latex": "If all closed geodesics of a surface metric are hyperbolic, then the closure of the set of periodic geodesics is a hyperbolic invariant set of the geodesic flow.",
        "y.reference_tool_type": "theorem",
    },
    "2401.07792v2_gap_0": {
        "x.anchor_hint": "Use the vanishing of the local $p$-torsion over $K_v$ to deduce $\\mathcal{E}(K_{\\infty,w})[p]=0$ for places above $p$.",
    },
    "2111.15096_gap_0": {
        "x.anchor_hint": "Use the homotopy-pullback theorem for $A_n$-maps to identify the fiberwise homotopy fiber as a fiberwise $A_\\ell$-space.",
        "y.reference_tool_latex": "The fiberwise homotopy pullback of fiberwise $A_n$-maps admits a canonical fiberwise $A_\\ell$-space structure.",
        "y.reference_tool_type": "theorem",
    },
    "2108.04421v3_gap_0": {
        "x.anchor_hint": "Apply the Kenyon-Wilson formula expressing grove connection probabilities in terms of the boundary measurements $L^\\delta_{\\varpi}$.",
    },
    "2107.06236_gap_0": {
        "x.anchor_hint": "Use the fixed-parameter linear-time algorithm for deciding whether a graph has crossing number at most $k$.",
    },
    "2101.04162_gap_1": {
        "x.anchor_hint": "Use the Levine-Morel description of algebraic cobordism over a perfect field as generated by smooth projective varieties.",
    },
    "2111.11975_gap_0": {
        "x.anchor_hint": "Use continuity of the action-filtered barcode under Legendrian isotopy.",
    },
    "1804.10581v2_gap_4": {
        "x.anchor_hint": "Use the optimality of the exponent $\\frac{1}{2}$ in the spectral inequality when $\\omega$ is a strict open subset of $M$.",
    },
    "1907.11400_gap_0": {
        "x.anchor_hint": "Use the splitting theorem that cutting along an ideal arc induces an injective algebra map on stated skein algebras.",
        "y.reference_tool_latex": "Cutting a surface $S$ along an ideal arc $c$ induces a natural injective algebra homomorphism from the stated skein algebra of $S$ to that of the cut surface $S'$.",
        "y.reference_tool_type": "theorem",
    },
    "2001.01410_gap_0": {
        "y.reference_tool_latex": "A rational inner function $\\Psi:\\mathbb{D}\\to \\mathcal{B}(\\mathcal{E})$ with finite-dimensional $\\mathcal{E}$ admits a realization with finite-dimensional auxiliary Hilbert space.",
        "y.reference_tool_type": "theorem",
    },
    "2407.19878v5_gap_0": {
        "y.reference_tool_latex": "$\\mathcal{C}_{\\lambda}=e^{-\\frac{3}{n}(n-\\lambda_1)}\\left(1+O\\left(\\frac{3}{n^2}\\right)\\right)$ for all $\\lambda\\vdash n$ satisfying $n-\\lambda_1\\ll n$.",
    },
    "2211.15609v4_gap_0": {
        "y.reference_tool_latex": "For a whole-plane GFF modulo \\(2\\pi\\chi\\), the σ-algebra \\(\\bigcap_{r>0} \\sigma(h|_{B(0,r)})\\) is trivial.",
        "y.reference_tool_type": "lemma",
    },
    "2206.00594v5_gap_0": {
        "x.anchor_hint": "Use Jaeger's lower bound on the feedback-vertex number of a cubic multigraph.",
        "y.reference_tool_latex": "Any cubic multigraph $H$ on $n$ vertices satisfies $\\operatorname{fvs}(H) \\ge \\frac{n+2}{4}$.",
        "y.reference_tool_type": "theorem",
    },
    "2211.07984v2_gap_0": {
        "x.anchor_hint": "Identify the stellohedron with the secondary polytope of the point configuration known as the mother of all examples.",
        "y.reference_tool_latex": "The stellohedron is combinatorially equivalent to the secondary polytope of the point configuration known as the mother of all examples.",
        "y.reference_tool_type": "theorem",
    },
    "2402.04151v2_gap_0": {
        "x.anchor_hint": "Use the joint lower semicontinuity of $W_\\infty$ with respect to weak convergence.",
        "y.reference_tool_latex": "The Wasserstein distance $W_\\infty$ is jointly lower semicontinuous with respect to weak convergence.",
        "y.reference_tool_type": "theorem",
    },
    "1908.08087_gap_1": {
        "y.reference_tool_latex": "There exist constants \\(C_3, C_4 > 0\\) such that the heat kernel \\(G_{\\delta}(x,y,s)\\) satisfies \\(G_{\\delta}(x,y,s) \\le C_3 s^{-n} e^{-d_{\\delta}(x,y)/(5s)}\\) for \\(0 < s < 1\\), and \\(G_{\\delta}(x,y,s) \\le C_4 s^{-n}\\) for all \\(s > 0\\).",
        "y.reference_tool_type": "theorem",
    },
    "2007.13103v1_gap_0": {
        "y.reference_tool_latex": "Let $A$ and $B$ be nonempty convex sets in topological vector spaces, with $A$ compact. If $f:A\\times B\\to \\mathbb{R}$ is convex and lower semicontinuous in the first variable and concave and upper semicontinuous in the second, then \\inf_{a\\in A}\\sup_{b\\in B} f(a,b) = \\sup_{b\\in B}\\inf_{a\\in A} f(a,b)$.",
        "y.reference_tool_type": "theorem",
    },
}

EXPLICIT_DROP_IDS: set[str] = {
    "2012.13786v1_gap_0",
    "2202.01436v2_gap_1",
    "2412.00476v3_gap_0",
    "1712.01412v3_gap_1",
    "2001.04379v4_gap_1",
    "2008.10019v2_gap_8",
    "2108.11152_gap_0",
    "2111.02812v3_gap_0",
    "2009.09426v2_gap_3",
    "2009.09426v2_gap_4",
    "2011.04195v2_gap_2",
    "2206.15188v2_gap_1",
    "2302.02995v3_gap_1",
    "2302.02995v3_gap_4",
    "2304.01823v4_gap_1",
    "2310.08832v3_gap_0",
    "2006.16425_gap_6",
    "2007.00588_gap_12",
    "1807.02702v3_gap_9",
    "1912.05737v6_gap_6",
    "2105.11585v3_gap_1",
    "2106.05947v4_gap_3",
    "2301.12513v2_gap_1",
}

NARRATIVE_TOOL_PATTERN = re.compile(
    r"^(If\\s+(Since|This|As|Observe|Using|By|It|Obviously|ion|e\\s+case)|Then\\b|We\\s+follow\\b|Following\\b)",
    re.I,
)
SUSPICIOUS_ANCHOR_PATTERN = re.compile(r"\\(\\s*,|^\\)|\\bThen\\.?$|\\bFollowing\\.?$|\\bwe again need to assume\\b|\\$\\s*_", re.I)
BROKEN_TOOL_TOKENS = (" heta_", " rac{", " igcap", " hight", " ext{", " imes B o ")
BROKEN_TOOL_REGEXES = (
    re.compile(r"\\end\{equation\*?\}"),
    re.compile(r"\\(?:cite|thref|eqref|label)\b"),
    re.compile(r"\\cf\b", re.I),
    re.compile(r"\bc\.f\.\b", re.I),
    re.compile(r"\bso by theorem\b", re.I),
    re.compile(r"\bby theorem\s+[0-9A-Za-z]", re.I),
    re.compile(r"\bthen and\b", re.I),
    re.compile(r"\bthen let\b", re.I),
    re.compile(r"\bwe may assume\b", re.I),
    re.compile(r"\bwe set\b", re.I),
    re.compile(r"\bit is well-known that\b", re.I),
    re.compile(r"^If\s+Changing\b", re.I),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Finalize a curated core-task dataset snapshot from a cleaned merged JSONL.")
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--summary", required=True)
    parser.add_argument("--review", required=True)
    parser.add_argument("--refresh-current", action="store_true")
    parser.add_argument("--current-output", default="construction/outputs/benchmark_dataset_current.jsonl")
    parser.add_argument("--current-summary", default="construction/outputs/benchmark_dataset_current.summary.json")
    return parser.parse_args()


def normalize_space(text: str) -> str:
    return re.sub(r"\\s+", " ", text or "").strip()


def get_nested(row: dict[str, Any], dotted: str) -> Any:
    current: Any = row
    for part in dotted.split("."):
        if not isinstance(current, dict):
            return None
        current = current.get(part)
    return current


def set_nested(row: dict[str, Any], dotted: str, value: Any) -> None:
    parts = dotted.split(".")
    current = row
    for part in parts[:-1]:
        current = current.setdefault(part, {})
    current[parts[-1]] = value


def apply_manual_fixes(row: dict[str, Any]) -> list[str]:
    applied: list[str] = []
    for dotted, value in MANUAL_FIXES.get(str(row.get("instance_id")), {}).items():
        set_nested(row, dotted, value)
        applied.append(dotted)
    return applied


def narrative_tool(text: str) -> bool:
    return bool(NARRATIVE_TOOL_PATTERN.search(normalize_space(text)))


def suspicious_anchor(text: str) -> bool:
    anchor = normalize_space(text)
    if not anchor:
        return True
    if anchor.count("$") % 2 == 1:
        return True
    return bool(SUSPICIOUS_ANCHOR_PATTERN.search(anchor))


def has_broken_tool_fragment(text: str) -> bool:
    value = text or ""
    return any(token in value for token in BROKEN_TOOL_TOKENS)


def suspicious_reference_tool(text: str) -> bool:
    value = normalize_space(text)
    if not value:
        return True
    if value.count("$") % 2 == 1:
        return True
    if has_broken_tool_fragment(value) or narrative_tool(value):
        return True
    return any(pattern.search(value) for pattern in BROKEN_TOOL_REGEXES)


def choose_rows(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[str(row.get("instance_id"))].append(row)

    selected: list[dict[str, Any]] = []
    dedup_removed: list[str] = []
    split_groups: dict[str, list[str]] = {}
    duplicate_groups = 0
    for instance_id, variants in grouped.items():
        if len(variants) == 1:
            selected.append(deepcopy(variants[0]))
            continue
        duplicate_groups += 1
        if instance_id in SPLIT_DUPLICATE_INSTANCE_IDS:
            new_ids = SPLIT_DUPLICATE_INSTANCE_IDS[instance_id]
            if len(new_ids) != len(variants):
                raise ValueError(f"Split id mapping mismatch for {instance_id}: expected {len(variants)} ids, got {len(new_ids)}")
            for new_id, row in zip(new_ids, variants):
                item = deepcopy(row)
                item["instance_id"] = new_id
                selected.append(item)
            split_groups[instance_id] = new_ids
            continue
        keep_idx = PREFERRED_DUPLICATE_OCCURRENCE.get(instance_id, 0)
        keep_idx = max(0, min(keep_idx, len(variants) - 1))
        selected.append(deepcopy(variants[keep_idx]))
        dedup_removed.extend([instance_id] * (len(variants) - 1))

    return selected, {
        "duplicate_groups": duplicate_groups,
        "dedup_rows_removed": len(dedup_removed),
        "split_groups": split_groups,
    }


def finalize_rows(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    kept: list[dict[str, Any]] = []
    review_drops: list[dict[str, str]] = []
    manual_fix_counts: Counter[str] = Counter()

    for row in rows:
        iid = str(row.get("instance_id"))
        applied = apply_manual_fixes(row)
        for dotted in applied:
            manual_fix_counts[dotted] += 1

        anchor = normalize_space(str(get_nested(row, "x.anchor_hint") or ""))
        tool = normalize_space(str(get_nested(row, "y.reference_tool_latex") or ""))
        tool_type = normalize_space(str(get_nested(row, "y.reference_tool_type") or ""))
        citation = normalize_space(str(get_nested(row, "z.citation_content") or ""))
        setup = normalize_space(str(get_nested(row, "x.global_context.setup") or ""))
        target = normalize_space(str(get_nested(row, "x.global_context.target_theorem") or ""))
        local = get_nested(row, "x.local_context")

        if iid in EXPLICIT_DROP_IDS:
            review_drops.append({"instance_id": iid, "reason": "explicit_drop_low_confidence_reference_tool"})
            continue
        if not setup or not target or local is None or not anchor or not tool or not tool_type or not citation:
            review_drops.append({"instance_id": iid, "reason": "missing_core_field_after_finalize"})
            continue
        if suspicious_reference_tool(tool):
            review_drops.append({"instance_id": iid, "reason": "reference_tool_is_suspicious_or_corrupted"})
            continue
        if suspicious_anchor(anchor):
            review_drops.append({"instance_id": iid, "reason": "anchor_hint_still_suspicious"})
            continue
        if has_broken_tool_fragment(tool):
            review_drops.append({"instance_id": iid, "reason": "reference_tool_has_broken_latex_fragment"})
            continue

        set_nested(row, "x.anchor_hint", anchor)
        set_nested(row, "y.reference_tool_latex", tool)
        set_nested(row, "y.reference_tool_type", tool_type)
        kept.append(row)

    summary = {
        "manual_fix_counts": dict(manual_fix_counts),
        "dropped_rows": len(review_drops),
        "dropped_examples": review_drops[:100],
    }
    return kept, summary


def validate(rows: list[dict[str, Any]]) -> dict[str, Any]:
    ids = [str(row.get("instance_id")) for row in rows]
    counts = Counter(ids)
    duplicate_ids = [iid for iid, count in counts.items() if count > 1]
    unknown_source = 0
    domain_counts: Counter[str] = Counter()
    source_type_counts: Counter[str] = Counter()
    tool_type_counts: Counter[str] = Counter()
    narrative_left = []
    suspicious_anchor_left = []
    broken_tool_left = []
    for row in rows:
        iid = str(row.get("instance_id"))
        source_type = str(get_nested(row, "z.source_type") or "")
        domain = str(get_nested(row, "strata.domain") or "")
        tool_type = str(get_nested(row, "y.reference_tool_type") or "")
        anchor = str(get_nested(row, "x.anchor_hint") or "")
        tool = str(get_nested(row, "y.reference_tool_latex") or "")
        if source_type == "unknown":
            unknown_source += 1
        source_type_counts[source_type] += 1
        domain_counts[domain] += 1
        tool_type_counts[tool_type] += 1
        if suspicious_reference_tool(tool):
            narrative_left.append(iid)
        if suspicious_anchor(anchor):
            suspicious_anchor_left.append(iid)
        if has_broken_tool_fragment(tool):
            broken_tool_left.append(iid)
    return {
        "rows": len(rows),
        "unique_instance_ids": len(counts),
        "duplicate_instance_ids": duplicate_ids,
        "remaining_unknown_source_type_count": unknown_source,
        "domain_counts": dict(domain_counts),
        "source_type_counts": dict(source_type_counts),
        "reference_tool_type_counts": dict(tool_type_counts),
        "remaining_narrative_tool_rows": narrative_left,
        "remaining_suspicious_anchor_rows": suspicious_anchor_left,
        "remaining_broken_tool_rows": broken_tool_left,
    }


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    summary_path = Path(args.summary)
    review_path = Path(args.review)
    current_output = Path(args.current_output)
    current_summary = Path(args.current_summary)

    rows = [json.loads(line) for line in input_path.open(encoding="utf-8") if line.strip()]
    selected_rows, dedupe_summary = choose_rows(rows)
    finalized_rows, finalize_summary = finalize_rows(selected_rows)
    validation = validate(finalized_rows)

    if validation["duplicate_instance_ids"]:
        raise SystemExit(f"Duplicate instance ids remain: {validation['duplicate_instance_ids'][:10]}")

    write_jsonl(output_path, finalized_rows)

    summary = {
        "input_file": str(input_path),
        "output_file": str(output_path),
        "rows_seen": len(rows),
        **dedupe_summary,
        **finalize_summary,
        **validation,
    }
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    review = {
        "input_file": str(input_path),
        "output_file": str(output_path),
        "split_duplicate_instance_ids": dedupe_summary["split_groups"],
        "manual_fix_counts": finalize_summary["manual_fix_counts"],
        "dropped_rows": finalize_summary["dropped_examples"],
        "remaining_narrative_tool_rows": validation["remaining_narrative_tool_rows"],
        "remaining_suspicious_anchor_rows": validation["remaining_suspicious_anchor_rows"],
        "remaining_broken_tool_rows": validation["remaining_broken_tool_rows"],
    }
    review_path.write_text(json.dumps(review, ensure_ascii=False, indent=2), encoding="utf-8")

    if args.refresh_current:
        shutil.copyfile(output_path, current_output)
        current_payload = dict(summary)
        current_payload["output_file"] = str(current_output)
        current_payload["backing_snapshot_file"] = str(output_path)
        current_summary.write_text(json.dumps(current_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
